import logging
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from .database import engine, Base, SessionLocal
from .models import domain  # register new models
from .api import health, auth, freshers, pm, demo, verify
from .seed.seed_v2 import seed_v2
from .config import settings

def init_db():
    """Create tables and run the idempotent seed.

    Called at import time so it runs reliably on serverless platforms (e.g. Vercel),
    where ASGI lifespan/startup events are not guaranteed to fire. Fully guarded so a
    transient DB hiccup or a concurrent cold-start race never crashes a request.
    """
    try:
        Base.metadata.create_all(bind=engine)
        db = SessionLocal()
        try:
            seed_v2(db)
        except Exception as e:  # e.g. concurrent seed race -> unique violation
            db.rollback()
            logging.getLogger("uvicorn.error").warning("Seed skipped: %s", e)
        finally:
            db.close()
    except Exception as e:
        logging.getLogger("uvicorn.error").warning("DB init deferred: %s", e)

def create_app() -> FastAPI:
    app = FastAPI(
        title="SkillFlow AI",
        description="Backend for fresher & PM dashboards. Stores AI results generated by the frontend; the backend performs NO AI generation.",
        version="2.0.0",
    )

    if settings.cors_origins.strip() == "*":
        app.add_middleware(
            CORSMiddleware,
            allow_origins=["*"],
            allow_credentials=False,
            allow_methods=["*"],
            allow_headers=["*"],
        )
    else:
        origins = [o.strip() for o in settings.cors_origins.split(",") if o.strip()]
        app.add_middleware(
            CORSMiddleware,
            allow_origins=origins,
            allow_credentials=True,
            allow_methods=["*"],
            allow_headers=["*"],
        )

    app.include_router(health.router)
    app.include_router(auth.router)
    app.include_router(freshers.router)
    app.include_router(pm.router)
    app.include_router(demo.router)
    app.include_router(verify.router)

    init_db()

    return app

app = create_app()
